apiVersion: v1
kind: Namespace
metadata:
  name: testspace 
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-udp-server
  namespace: testspace
spec:
  selector:
    app: testudp-server
  ports:
    - protocol: UDP
      port: 8805
      targetPort: 8805
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testudp-server
  namespace: testspace
  labels:
    app: udpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udpserver
  template:
    metadata:
      labels:
        app: udpserver
    spec:
      containers:
      - name: udpserver
        image: docker.io/ajaythakuronf/testudp-1:latest
        command: ["bash", "-xc"]
        args:
        - /go/src/server/server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testudp-client
  namespace: testspace
  labels:
    app: udpclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udpclient
  template:
    metadata:
      labels:
        app: udpclient
    spec:
      containers:
      - name: udpclient
        image: docker.io/ajaythakuronf/testudp-1:latest
        command: ["bash", "-xc"]
        args:
        - /go/src/client/client

